update instructor bios
ExoKomodo/Edu pull request #43
Opened 2023-03-30 20:25 UTC by brandonapol

Closes #42

2023-03-30 20:28 UTC, brandonapol commented
The second section of the landing page has two identical paragraphs, I used a component but I think I am going to migrate it into one component with two parts so I can differentiate the content (hard code rather than props). Otherwise we'll be passing paragraphs into the components as props which is also OK I guess but feels weird to me - let me know if you prefer one or the other means and I'll make another commit with that update shortly

2023-03-30 20:40 UTC, JamesOrson requested changes

2023-03-30 20:40 UTC, JamesOrson commented on client/src/components/InfoTile.vue
> +
Nit: Remove empty line

2023-03-30 20:40 UTC, JamesOrson commented on client/src/components/Instructors.vue
> +                    <p class="text-virgil xs:hidden sm:block">James is a chief Site Reliability Engineer at Pure Storage Solutions
Just call it `Pure Storage`

2023-03-30 20:40 UTC, JamesOrson commented on client/src/components/Instructors.vue
> +                        in San Jose, California. He and his wife love their daughter, eating healthy, and participating
`Mountain View, California`

2023-03-31 00:32 UTC, brandonapol commented
sorry for commit name, will improve my vim skills

2023-03-31 03:55 UTC, JamesOrson requested changes

2023-03-31 03:55 UTC, JamesOrson commented on client/src/components/InfoTile.vue
> +            Learn more about coding with our highly qualified instructors. <a href="#">EK.edu</a> is oriented around
What exactly is this `href` trying to point to?

If you want the home page, it should be `/` not `#`

2023-04-01 19:36 UTC, JamesOrson approved these changes

2023-04-01 19:38 UTC, merged