35 bug styling is not readable on blog page
ExoKomodo/Edu pull request #72
Opened 2023-04-07 23:25 UTC by brandonapol

Closes #50 

Was going to quickly take care of this, but I am not seeing the blog posts whatsoever. I'm running the back end locally as well. Not sure what the deal is. Happy to style blog posts, just can't see any. But I did fix the navbar issues

2023-04-07 23:30 UTC, brandonapol commented
Still hitting CORS issues locally. I will use some dummy data for a blog and pass that through temporarily so I can see and style.

2023-04-16 01:06 UTC, JamesOrson requested changes

2023-04-16 01:06 UTC, JamesOrson commented on server/Data/blogs/1.html
> -<h1>Blog #1, friends</h1>
This should retain the h1 because we embed this HTML directly

If we already have an h1, drop this ti an h2 or something

2023-04-16 01:08 UTC, brandonapol commented on server/Data/blogs/1.html
> -<h1>Blog #1, friends</h1>
It is literally at present rendering the tags verbatim. Better to target the tailwind at final location for styling instead

2023-04-16 01:13 UTC, brandonapol commented on server/Data/blogs/1.html
> -<h1>Blog #1, friends</h1>
![Screen Shot 2023-04-15 at 9 13 15 PM](https://user-images.githubusercontent.com/72466214/232260854-6ecc3d78-b8f
![Screen Shot 2023-04-15 at 9 13 46 PM](https://user-images.githubusercontent.com/72466214/232260865-0e95e7c6-6fac-4f9d-b194-52701d68fcd2.png)
9-48af-9357-27fc9044db94.png)

2023-04-16 01:14 UTC, brandonapol commented on server/Data/blogs/1.html
> -<h1>Blog #1, friends</h1>
![Screen Shot 2023-04-15 at 9 14 38 PM](https://user-images.githubusercontent.com/72466214/232260892-a08a7104-0dbe-4d60-9eda-326693628018.png)

2023-04-16 01:15 UTC, brandonapol commented on server/Data/blogs/1.html
> -<h1>Blog #1, friends</h1>
If your intention is to eventually use a markdown-style engine or HTML rendering then we will have to change the approach some

2023-04-16 02:24 UTC, JamesOrson commented
Now to actually render as html, the content needs to use the v-html attribute: https://vuejs.org/guide/essentials/template-syntax.html#raw-html

Once that is done, you're good!

2023-04-17 01:57 UTC, JamesOrson approved these changes

2023-04-18 13:07 UTC, merged